# Official documentation at http://goreleaser.com
project_name: simple-bootstrap-node
builds:
  - env:
      - CGO_ENABLED=0
    binary: simple-bootstrap-node
    goos:
      - windows
      - linux
      - darwin
    ldflags:
      - -w
      - -s
dist: release
archives:
  - name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      amd64: amd64
      arm64: arm64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next-{{.ShortCommit}}"
changelog:
  skip: true
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
